// <auto-generated />
using BasicBilling.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicBilling.API.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20231015225519_AddingSeedsToDB")]
    partial class AddingSeedsToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("BasicBilling.API.Models.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Period", "ClientId");

                    b.ToTable("BillItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientId = 1L,
                            Period = "202301",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 2L,
                            ClientId = 1L,
                            Period = "202301",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 3L,
                            ClientId = 1L,
                            Period = "202301",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 4L,
                            ClientId = 1L,
                            Period = "202302",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 5L,
                            ClientId = 1L,
                            Period = "202302",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 6L,
                            ClientId = 1L,
                            Period = "202302",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 7L,
                            ClientId = 2L,
                            Period = "202301",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 8L,
                            ClientId = 2L,
                            Period = "202301",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 9L,
                            ClientId = 2L,
                            Period = "202301",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 10L,
                            ClientId = 2L,
                            Period = "202302",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 11L,
                            ClientId = 2L,
                            Period = "202302",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 12L,
                            ClientId = 2L,
                            Period = "202302",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 13L,
                            ClientId = 3L,
                            Period = "202301",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 14L,
                            ClientId = 3L,
                            Period = "202301",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 15L,
                            ClientId = 3L,
                            Period = "202301",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 16L,
                            ClientId = 3L,
                            Period = "202302",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 17L,
                            ClientId = 3L,
                            Period = "202302",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 18L,
                            ClientId = 3L,
                            Period = "202302",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 19L,
                            ClientId = 4L,
                            Period = "202301",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 20L,
                            ClientId = 4L,
                            Period = "202301",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 21L,
                            ClientId = 4L,
                            Period = "202301",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 22L,
                            ClientId = 4L,
                            Period = "202302",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 23L,
                            ClientId = 4L,
                            Period = "202302",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 24L,
                            ClientId = 4L,
                            Period = "202302",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 25L,
                            ClientId = 5L,
                            Period = "202301",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 26L,
                            ClientId = 5L,
                            Period = "202301",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 27L,
                            ClientId = 5L,
                            Period = "202301",
                            Status = false,
                            Category = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 28L,
                            ClientId = 5L,
                            Period = "202302",
                            Status = false,
                            Category = "SEWER"
                        },
                        new
                        {
                            Id = 29L,
                            ClientId = 5L,
                            Period = "202302",
                            Status = false,
                            Category = "WATER"
                        },
                        new
                        {
                            Id = 30L,
                            ClientId = 5L,
                            Period = "202302",
                            Status = false,
                            Category = "ELECTRICITY"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Joseph Carlton"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Maria Juarez"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Albert Kenny"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Jessica Phillips"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Charles Johnson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
